# syntax=docker/dockerfile:1.3-labs
FROM ubuntu:22.04
MAINTAINER Richard Phillis <rphillis@studiosity.com>

WORKDIR /usr/local/src

RUN apt-get update && apt-get install -y \
    libpq5 \
    libpq-dev \
    python3 \
    python3-dev \
    python3-pip \
    git \
    && pip3 install psycopg2 sqlalchemy tornado \
    && rm -rf /var/lib/apt/lists/* \
    && useradd app \
    && mkdir -p /home/app \
    && chown app /home/app \
    && git clone https://github.com/binocvlar/powa-web.git powa-web.git \
    && apt-get purge -y --auto-remove libpq-dev python3-dev python3-pip git

COPY <<-"EOF" /etc/powa-web.conf

servers={
  'prd-pgl-09.yak.run': {
    'host': 'prd-pgl-09.yak.run',
    'port': '5432',
    'database': 'powa',
  },
  'prd-pgl-10.yak.run': {
    'host': 'prd-pgl-10.yak.run',
    'port': '5432',
    'database': 'powa',
  },
}
cookie_secret="<REDACTED>"
EOF

USER app

EXPOSE 8888
CMD ["python3", "powa-web.git/run_powa.py"]
